require: rubocop-rails

Layout/AlignHash:
  Exclude:
    - config/initializers/simple_form_bootstrap.rb

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - config/initializers/simple_form_bootstrap.rb

Metrics/LineLength:
  Exclude:
    - bin/setup
    - bin/rake
    - bin/rails
    - bin/spring
    - config/initializers/content_security_policy.rb
    - config/initializers/simple_form*.rb

AllCops:
  Exclude:
    - bin/bundle
    - bin/webpack-dev-server
    - bin/webpack
    - bin/yarn
    - node_modules/node-sass/src/libsass/*
    - node_modules/node-sass/src/libsass/**/*
Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb
Style/Documentation:
  Enabled: false
