default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: proto_development
  user: proto
  password: proto

test:
  <<: *default
  database: proto_test
  user: proto
  password: proto

production:
  <<: *default
  database: proto
